[package]
name = "yuqi"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
colored = "3.0.0"
regex = "1.11.1"
regex-split = "0.1.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
